### ISSUE TITLE
Installation on Linux systems

### ISSUE THREAD

**Issue by dgilge** [googlefonts/pyfontaine#113]
I was wondering why there is an installation guide for macOS only. So, here is how I managed to install pyfontaine on Debian:

`apt-get install libicu-dev` (`pkg-config` is a build dependency and doesn't have to be installed separately)

`pip install fontaine` (or actually `poetry add fontaine`)

If someone could confirm that this is correct it would be nice to add this to the readme or I could open a PR.

**Comment by davelab6** [comment]
@dgilge its because if you know how to be a Debian user, you probably know how to figure out how to  install it. But its a fine suggestion, so I'll add that now.
