### ISSUE TITLE
Hilbert Curve diagram support

### ISSUE THREAD

**Issue by davelab6** [googlefonts/pyfontaine#72]
I removed mention of the Hilbert curves in https://github.com/davelab6/pyfontaine/commit/2447ff0a8c1dbe52304f07daee1d4522bcabfce9 as the `--coverage` arg is no longer recognised, but it would be good to bring this back someday.

**Comment by felipesanches** [comment]
Not sure how actually useful is this, even though it is a neat idea ;-)

![Screenshot at 2019-10-17 19:18:10](https://user-images.githubusercontent.com/213676/67051911-15511080-f12c-11e9-880c-8ed4e663afca.png)
